.github/workflows/clean-up-cache.yaml, README.md, RELEASE_NOTES.md
If you'd like to propose a new feature or change,
please open an issue to discuss the change or find an existing issue.
Add workflow to clean-up action cache on PR closure
Fixes #7
=> Add workflow to clean-up action cache on PR closure

.github/workflows/add-to-project.yaml, .github/workflows/clean-up-storage.yaml
=> Add jq to artefact clean up script

.github/workflows/release-notes.yaml, RELEASE_NOTES.md
=> specify manually branch

.github/workflows/markdown.yaml, .github/workflows/release-notes.yaml, RELEASE_NOTES.md
replace original prettier action with customised one to solve some of the issue faced.
* don't fail on dry run
* support push_options
=> use customized prettier action

.github/workflows/markdown.yaml, .github/workflows/release-notes.yaml
Release notes workflow: remove work around to fix broken lists
* Release notes workflow: remove work around to fix broken lists
Fixes #22
=> release notes workflow: remove work around to fix broken lists

.github/workflows/markdown.yaml, RELEASE_NOTES.md
Exclude vendor folder from markdown check.
=> Exclude vendor folder from markdown check.

.github/workflows/markdown.yaml, RELEASE_NOTES.md
Exclude vendor folder from markdown links check.
=> markdown workflow: exclude `vendor` folder from links check

.github/workflows/clean-up-docker.yaml, .github/workflows/docker.yaml, .github/workflows/golang.yaml, README.MD, RELEASE_NOTES.md
Add Docker, Go lang and Docker Clean Up workflows
Add Docker, Go lang and Docker Clean Up workflows
N/A
=> Add Docker, Go lang and Docker Clean Up workflows

.github/workflows/golang.yaml, README.MD, RELEASE_NOTES.md
Add docker login on test and benchmark golang workflows
- Add docker login on golang test workflow
- Add docker login on golang benchmark workflow
N/A
=> golang: add docker login on test and benchmark workflows

.github/config/wordlist.txt, .github/dependabot.yml, .github/workflows/add-to-project.yaml, .github/workflows/check-pr.yaml, .github/workflows/clean-up-docker.yaml, .github/workflows/clean-up-storage.yaml, .github/workflows/docker.yaml, .github/workflows/golang.yaml, .github/workflows/license.yaml, .github/workflows/markdown.yaml, .github/workflows/release-notes.yaml, .github/workflows/test-upload.yaml, .gitignore, RELEASE_NOTES.md
Add dependabot for github actions.
Add dependabot.yml
N/A
=> Add dependabot

.github/workflows/golang.yaml, RELEASE_NOTES.md
Skip code coverage if the actor is Dependabot
- Add conditions to skip code coverage steps if the actor is dependabot[bot]
N/A
=> golang workflow: skip code coverage if the actor is dependabot

.github/workflows/golang.yaml, RELEASE_NOTES.md
add input variable for alert threshold to golang workflow
- add input variable for alert threshold to golang workflow
N/A
=> golang workflow: add input variable for alert threshold

.github/workflows/markdown.yaml, RELEASE_NOTES.md
markdown workflow: Use quite mode for link checker
* markdown workflow: Use quite mode for link checker
Fixes #111
=> markdown workflow: Use quiet mode for link checker

.github/workflows/deployment.yaml, README.MD, RELEASE_NOTES.md
Add a workflow to commit container image tags to `k8s-deployments`
- Add `deployment.yaml`
Fixes #114
=> Add the deployment workflow

.github/workflows/deployment.yaml, RELEASE_NOTES.md
Fix the broken PRs list filter returning all PRs instead of the required one.
- Use ref label instead of ref for filtering
N/A
=> Fix deployment workflow on PRs

.github/workflows/docker.yaml, RELEASE_NOTES.md
docker wf: support concurrent image builds
support concurrent image builds
N/A
=> docker wf: support concurrent image builds

.github/workflows/golang.yaml
golang  workflow: fix changes check
N/A
N/A
=> golang  workflow: fix changes check

.github/config/release-config.json, .github/workflows/check-pr.yaml, RELEASE_NOTES.md
It is useful to include "customer" as label to identify features or configurations specific to a customer.
* Allow PRs with label `customer`
* Manage issue with label `customer`
* Manage release notes for PRs with label `customer`
N/A
=> Support Customer Label

.github/workflows/docker.yaml, .github/workflows/golang.yaml, RELEASE_NOTES.md
Cache trivy db daily to avoid incurring in the TOO MANY REQUEST issue.
* Cache trivy db daily in golang wf
* Cache trivy db daily in docker wf
N/A
=> Golang & Docker workflows: add db caching to trivy

.github/workflows/new-release.yaml, README.MD, RELEASE_NOTES.md
Add workflow to create a new release and update version in packaging files (e.g. `pyproject.toml` for python)
* Add workflow to create a new release
* Support of update version in packaging files (e.g. `pyproject.toml` for python)
N/A
=> Add workflow to create a new release

.github/workflows/golang.yaml, RELEASE_NOTES.md
Use SonarSource/sonarqube-scan-action
* Use SonarSource/sonarqube-scan-action
Fixes #149
=> Use SonarSource/sonarqube-scan-action

.github/workflows/docker.yaml, RELEASE_NOTES.md
Pass github token to docker build as secret
Pass github token to docker build as secret
N/A
=> Pass github token to docker build as secret

.github/workflows/release-notes.yaml, RELEASE_NOTES.md
This PR fixes the sbom generation on release. We were not checking out the repo code, so the trivy was using an empty folder to generate the sbom.
* checkout code to correctly generate sbom
N/A
=> Release notes workflow: fix sbom generation

.github/workflows/golang.yaml, RELEASE_NOTES.md
This change adds a `pull-dvc-datasets` input in the `golang.yml` workflow to install dvc to run the tests.
* golang workflow: support dvc data pulling for tests
N/A
=> golang workflow: support dvc data pulling for tests

.github/workflows/docker.yaml, RELEASE_NOTES.md
docker workflow: pass token to prebuild step
* docker workflow: pass token to prebuild step
https://github.com/zaphiro-technologies/grafana-dashboards/pull/187
=> docker workflow: pass token to prebuild step

.github/workflows/approve-and-merge.yaml
This PR adds `approve-and-merge` workflow that automatically approve and merge PRs by dependabot
* add approve-and-merge` workflow
N/A
=> approve-and-merge: add workflow that automatically approve and merge PRs by dependabot

.github/workflows/docker.yaml, RELEASE_NOTES.md
Run Docker Build after Dependabot merged PR
- Run Docker Build after Dependabot merged PR
N/A
=> Run Docker Build after Dependabot merged PR

.github/workflows/python.yaml, RELEASE_NOTES.md
This PR adds a generic python workflow following the golang one structure.
-Add a generic python workflow following the golang one structure.
Fixes #150
=> Add python workflow

.github/workflows/approve-and-merge.yaml, RELEASE_NOTES.md
Approve-and-merge workflow: rebase before approval
Approve-and-merge workflow: rebase before approval
N/A
=> Approve-and-merge workflow: rebase before approval

.github/workflows/python.yaml, RELEASE_NOTES.md
Python workflow: add `poetry.lock` and `pyproject.toml` to change list
* Python workflow: add `poetry.lock` and `pyproject.toml` to change list
N/A
=> Python workflow: add `poetry.lock` and `pyproject.toml` to change list

.github/workflows/new-release.yaml, README.MD, RELEASE_NOTES.md
The new release workflow has been improved to use the make release function, replacing language-specific steps for updating version numbers in project files.
=> new-release workflow: delegate to makefile the update of project files

.github/workflows/deployment.yaml
deployment: fix app token scope to push to k8s-deployments
- Generate token to access k8s-deployments
=> deployment: fix app token scope
