- .github/workflows/clean-up-cache.yaml
- .github/workflows/clean-up-storage.yaml
- .github/workflows/test-upload.yaml
- README.md
- RELEASE_NOTES.md
If you'd like to propose a new feature or change,
please open an issue to discuss the change or find an existing issue.
Add Clean Up Artefact job
Fixes #10
> Add job to clean up artefacts on pr closure

- .github/workflows/add-to-project.yaml
- RELEASE_NOTES.md
Make labels configurable as inputs in add-to-project workflow
* add input field for labels and set default value as the current static value
Fixes #25
> add-to-project workflow: make labels configurable as inputs

- .github/workflows/add-to-project.yaml
- RELEASE_NOTES.md
add-to-project workflow: make project url configurable as input parameter 
add-to-project workflow: make project url configurable as input parameter 
Fixes #32
> add-to-project workflow: make project url configurable as input parameter 

- .github/config/release-config.json
- RELEASE_NOTES.md
Release-notes wf: fix default configuration to include only current PR among open PRs
* fix replacing strings with booleans 
Fixes #26
> Release-notes wf: fix default configuration to include only current PR among open PRs

- .github/workflows/add-to-project.yaml
- README.MD
- RELEASE_NOTES.md
automatically add reviewers without need of CODEOWNERS, reviewers are added if and only if the PR is not in draft mode.
The recommendation is to start the PR in draft mode, and move it to ready only when actually ready for review.
While CODEOWNERS is very powerful, it would require to add such file to all repositories.
* add specified team as collaborator (default team is `backend-devs`)
* add rowi1de/auto-assign-review-teams@v1.1.3 to add-to-project workflow
Fixes #38
> add-to-project workflow: automatically add reviewers without need of CODEOWNERS

- .github/workflows/add-to-project.yaml
- RELEASE_NOTES.md
Check that PR is ready before assigning reviewer.
Add check on PR readiness.
Fixes #39
> add-to-project workflow: Fix assignment of reviewers also when PR is still in draft mode

- .github/workflows/add-to-project.yaml
- RELEASE_NOTES.md
set PR in progress or ready depending on status
add conditional action to set PR in progress or ready depending on status
Fixes #49
> add-to-project workflow: set PR on creation to `🏗 In progress` and  when ready to `🔖 Ready`

- .github/workflows/markdown.yaml
- RELEASE_NOTES.md
markdown workflow: configure globs via input parameter
* globs for markdown linter are now configurable via a input parameter.
N/A
> markdown workflow: configure globs via input parameter and remove not working `--ignore-path` for `.github/config/.prettierignore`

- .github/workflows/markdown.yaml
- RELEASE_NOTES.md
markdown wf: run jobs only when there are changes to markdown related files
* markdown wf: run jobs only when there are changes to markdown related files
Fixes #51
> markdown workflow: run jobs only when there are changes to markdown related files

- .github/workflows/add-to-project.yaml
- RELEASE_NOTES.md
Add support for assign multiple teams as reviewers (comma separated without space)
* Split teams using comma and iterate adding rights
Fixes #41
> add-to-project workflow: add support to assign multiple teams as reviewers (comma separated without space)

- .github/workflows/docker.yaml
- RELEASE_NOTES.md
Add pre-build step in docker workflow to run the `ci-pre-build` task from Makefile, if the file exists.
This, as example, enables Go builds without vendor folder to download private dependencies before the docker build.
Add pre-build step in docker workflow
N/A
> docker workflow: add `pre-build` step

- .github/config/.licenserc.yaml
- .github/workflows/add-to-project.yaml
- .github/workflows/check-pr.yaml
- .github/workflows/clean-up-docker.yaml
- .github/workflows/clean-up-storage.yaml
- .github/workflows/docker.yaml
- .github/workflows/golang.yaml
- .github/workflows/license.yaml
- .github/workflows/markdown.yaml
- .github/workflows/release-notes.yaml
- .github/workflows/test-upload.yaml
- .gitignore
- LICENSE
- README.MD
- RELEASE_NOTES.md
Add workflow to support license management
* add configurable workflow to support license management (add header, check dependencies)
* add example configuration
Fixes #48
> add workflow to support license management

- .github/workflows/docker.yaml
- RELEASE_NOTES.md
Add git and build information as docker build args.
The following build-args have been added:
- GIT_REV: commit hash
- GIT_VERSION: branch name or tag
- GIT_URL: URL of source repository
- BUILD_DATE: ISO 8601 date and time of build
> docker workflow: add git and build information as build arguments

- .github/config/wordlist.txt
- .github/workflows/golang.yaml
- RELEASE_NOTES.md
I propose to update the annotation for codecoverage to error [docs](https://github.com/barecheck/code-coverage-action#:~:text=made%20in%20PR-,show%2Dannotations,-no), because warning inserts to many annotation making unreadable the PRs
- Updated `golang.yaml` workflow
> Lower annotation pollution on PRs

- .github/config/.prettierignore
- .github/config/wordlist.txt
- .github/workflows/markdown.yaml
- RELEASE_NOTES.md
- __tests__/test.md
Support prettier ignore configuration load from `.github/config/.prettierignore`
Support prettier ignore configuration load from `.github/config/.prettierignore`
Fixes #61
> markdown workflow: support correctly `.prettierignore`

- .github/workflows/golang.yaml
- RELEASE_NOTES.md
Even though only errors are shown, it makes reading PRs difficult. Therefore, I would remove all the annotations.
> golang: remove code coverage annotations

- .github/workflows/docker.yaml
- .github/workflows/markdown.yaml
- .github/workflows/release-notes.yaml
- RELEASE_NOTES.md
docker workflow: execute only if the pr actor is not dependabot or labels contains `docker`
* docker workflow: execute only if the pr actor is not dependabot or labels contains `docker`
* markdown and release note workflow: add [[dependabot skip]](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#allowing-dependabot-to-rebase-and-force-push-over-extra-commits) to comment
Fixes #98
> docker workflow: execute only if the pr actor is not dependabot or labels contains `docker`

- .github/workflows/golang.yaml
- RELEASE_NOTES.md
Move sonarcloud checks to test job
Move sonarcloud checks to test job
N/A
> Move sonarcloud checks to test job

- .github/workflows/docker.yaml
- .github/workflows/golang.yaml
- RELEASE_NOTES.md
Support golang build caching in docker builds
* docker workflow: support golang build caching
* golang workflow: run only if golang changes
N/A
> docker workflow: support golang build caching

- .github/workflows/deployment.yaml
- RELEASE_NOTES.md
deployment workflow: fix tag version extraction
- deployment workflow: fix tag version extraction
N/A
> deployment workflow: fix tag version extraction

- .github/workflows/golang.yaml
- RELEASE_NOTES.md
The change of sql files and docker files may impact the behaviour of the applications, so we should run tests when such changes occurs.
* golang workflow: include sql files in golang changes filter
* golang workflow: include docker compose files in golang changes filter
N/A
> golang workflow: include `.sql` and `.docker/*.yml` files in golang changes filter

- .github/workflows/docker.yaml
- RELEASE_NOTES.md
docker workflow: add javascript mode for cache
* docker workflow: add javascript mode for cache
N/A
> docker workflow: add javascript mode for cache

- .github/workflows/markdown.yaml
- RELEASE_NOTES.md
Fix link check for `vendor` folders in subdirectories
Fix link check for `vendor` folders in subdirectories
N/A
> Fix link check for `vendor` folders in subdirectories

- .github/workflows/docker.yaml
This ensures that the docker.yml action runs on repos that rely on git submodule.
We enable setting the checkout `submodules` by introducing an action input `initialize-submodules`.
This was tested successfully on a private repository.
> docker workflow: support submodules initialisation

- .github/workflows/docker.yaml
- RELEASE_NOTES.md
support private repository checkout for submodules
* docker workflow: support private repository checkout
- https://github.com/zaphiro-technologies/incipient-fault-prediction/pull/2
> docker workflow: support private repository checkout

- .github/workflows/check-pr.yaml
- .github/workflows/docker.yaml
- .github/workflows/license.yaml
- .github/workflows/markdown.yaml
- RELEASE_NOTES.md
Reduce number of wf run when pr are in draft mode
* Run docker build only if PR is not draft
* Run pr check only if PR is not draft
N/A
> Reduce number of wf run when pr are in draft mode

- .github/workflows/docker.yaml
- RELEASE_NOTES.md
While not ideal, the current fledge-power docker build process relies on github to build plugins from zaphiro's private repositories. So we need a way to pass a token able to clone  zaphiro's private repositories to the docker build.
- Pass Github Token to Docker build process
- https://github.com/zaphiro-technologies/fledge-power-demo/pull/19
> Pass Github Token to Docker build process

- .github/workflows/docker.yaml
- RELEASE_NOTES.md
In reverse PRs (main -> branch) the docker build uses the tag main instead of branch, allowing unapproved code to reach main and making the content of main unpredictable. This fix resolves the issue tanks to the updated priorities on tags type, allowing the PR and branch name to be populated and used as tags, instead of the only "main" (that usually had high priority).
- Added explicit priorities to the tags type in the "docker.yaml" workflow file.
- Raised event=pr priority to '800'
- Raised event=branch priority to '800'
Fixes #185
> docker workflow: updated tags type priority values

- .github/workflows/add-to-project.yaml
- .github/workflows/approve-and-merge.yaml
- .github/workflows/check-pr.yaml
- .github/workflows/deployment.yaml
- .github/workflows/golang.yaml
- .github/workflows/license.yaml
- .github/workflows/markdown.yaml
- .github/workflows/new-release.yaml
- .github/workflows/python.yaml
- .github/workflows/release-notes.yaml
- RELEASE_NOTES.md
This PR replaces different PAT secrets - embedding different authorisations - with github app tokens.
- Replace `REPO_PAT` used to admin repositories (including access control) and related workflows.
- Replace `REPO_PRIVATE_READ_PAT` used to access other private repositories.
- Replace `ADD_TO_PROJECT_PAT` used to add issues to project.
To achieve the scope, the github app was granted the following authorisations:
Repo permissions:
- Read access to actions, members, metadata, and packages
- Read and write access to administration, code, issues, pull requests, and workflows
Organisation permissions:
- Read and write access to organization projects
N/A
> Replace PAT secrets with github app tokens

- .github/workflows/add-to-project.yaml
- .github/workflows/approve-and-merge.yaml
- .github/workflows/deployment.yaml
- .github/workflows/docker.yaml
- .github/workflows/golang.yaml
- .github/workflows/license.yaml
- .github/workflows/markdown.yaml
- .github/workflows/new-release.yaml
- .github/workflows/python.yaml
- .github/workflows/release-notes.yaml
- RELEASE_NOTES.md
This PR modifies workflows to use official action to create github app tokens and support additional repositories scoping. The additional scoping is required for actions that import content from other private repositories that the current one. For example in the golang workflow, when not using vendoring.
* use official action to create github app tokens
* support additional repositories scoping
N/A
> workflows: use official action to create github app tokens and support additional repositories scoping
